---
title: "Conferences"
subtitle: "Selected list of talks and presentations at various conferences"
---

## Invited Talks & Presentations

-  FORCE11 Scholarly Communication Institute (FSCI) 2024 @ UCLA, CA, United States - 3-days in-person course titled '[Making Research More Transparent with Quarto and RStudio](https://force11.org/fsci/post/course-list-with-abstracts-2024/#C03)' with co-instructor Dong Danping. 
-  Singapore Rising Scholars Conference 2024 @ SMU, Singapore - Seminar titled '[Streamlined Workflow for Qualitative Data Analysis with Whisper and ATLAS.ti](https://ink.library.smu.edu.sg/library_research/219/)' with co-presenters Dong Danping and Bryan Leow
-  Access Lab 2024 @ Online - Keynote presentation titled 'Beyond the books: Librarians as key partners in the AI-enhanced research and education'.
-  13th International CALIBER 2022 Conference @ BHU, Varanasi, UP, India - Theme Speaker presentation titled '[The emerging area of Data Services: A case of SMU Libraries](https://ink.library.smu.edu.sg/library_research/204/)'.
-  SAUL Copyright Seminar 2022 @ SMU, Singapore - Moderated '[Panel Discussion on Text and Data Mining](https://ink.library.smu.edu.sg/saulcopyright2022/Program/Recordings_slides/3/)'. The session's main theme was to explore the implications of the new amendments in Singapore Copyright Law, specifically the exception for text and data mining (TDM), on academics and librarians in Singapore.


## Organising Committee Works

-  LAS-PPM Conference 2021
-  Library Association Singapore (LAS) Conference 2019
-  [WordCamp Singapore 2019](https://singapore.wordcamp.org/2019/)
-  [WordCamp Singapore 2016](https://singapore.wordcamp.org/2016/)