---
title: "Teaching"
subtitle: "Selected list of teaching activities and workshops"
---

## 2024

- [Introductory R for Social Sciences](https://bellaratmelia.github.io/introductory-r-socsci/) - Comprises of 5 sessions of 2 hours each. 
    - AY 23/24 Term 2, Jan - Feb 2024 
    - AY 24/25 Term 1, Aug - Sep 2024

- Workshops in AI for Research Week 2024 (May 2024)
    - [Try it Together: Transcribe Your Audio with Whisper API](https://ink.library.smu.edu.sg/ai_research_week/Programme/Programme/3/)
    - [Try it together - AI-powered search tools: Elicit, SciSpace, Connected Papers, Researchrabbit, and Undermind.ai](https://ink.library.smu.edu.sg/ai_research_week/Programme/Programme/2/) - with co-instructors [Aaron Tay](http://musingsaboutlibrarianship.blogspot.com/) and Ooi Kooi Cheng


## 2023

- Introductory R for Social Sciences (AY 23/24 Term 1, Aug - Sep 2023) - Comprises of 4 sessions of 1.5 hours each. 
- [Data Carpentry (Social Sciences with R) for SMU](https://bellaratmelia.github.io/2023-11-29-smulib-dc/) (29-30 Nov 2023) - Open only to PhD students and research staff of SMU
- Volunteering at other Carpentries courses:
    - [Data Carpentry (Social Sciences with R) for Carnegie Mellon University](https://rsangole.github.io/2023-11-15-cmu-online/)
    - [Software Carpentry (Python) for TU Delft/University of Twente](https://4turesearchdata-carpentries.github.io/2023-05-30-Twente/) (May 2023)
    - [Software Carpentry (Python) for TU Delft/University of Twente](https://4turesearchdata-carpentries.github.io/2023-11-06-twente-online/) (November 2023)


## 2022

- [Library Carpentry for SMU Librarians](https://bellaratmelia.github.io/2022-06-29-smulibcarpentry/) (29-30 Jun 2022)